# This file has three standard purposes:
# 1. It contains the title of the package.
# 2. It contains the filename of the output file. This is to make the package structure independent of the application.
# 3. It contains basic information about the tests which need to be run (Soon(TM)).

title: Addition

statement: doc/statement.txt

examples:
  - input: doc/example1.in
    output: doc/example1.out
  - input: doc/example2.in
    output: doc/example2.out

testInput: input.in
userOutput: user.out